"""Package a converted/merged file as a loose-file mod for DMM ("Definitive Mod
Manager") and other DMM-family loose-file-aware managers (CDUMM, Crimson Browser).

**Verified against real data, not guessed from documentation:** the user has a
real, running DMM install with real, currently-mounted mods. Inspecting them
directly confirms the actual on-disk format:

- Every real mod (regardless of manifest dialect) drops its replacement files
  under a ``files/`` directory using the game's own real VFS-relative path,
  e.g. ``files/character/cd_phw_00_lb_00_0182.pac``. DMM mounts these as a
  virtual overlay -- it does **not** require patching the base game's real
  ``.paz``/``.pamt``/``.papgt`` archives in place at all. This is a much
  safer default than raw in-place archive patching (see
  ``core.game_patch_service.repack_relative_files`` in CrimsonForge, still
  usable separately for the rare case where a loose-file overlay isn't
  accepted): uninstalling is just deleting/disabling the mod folder in DMM,
  and the base game files are never touched.
- CrimsonForge itself (the same tool this project's merge/patch workflow
  already uses) ships its **own** real, already-in-the-wild loose-mod export
  format for exactly this purpose -- confirmed from a real mod actually
  generated by CrimsonForge and mounted in the user's DMM
  ("Proxima Shell Mesh Mod", generator=CrimsonForge): a ``manifest.json``
  (``schema_version: 1``, ``kind: "mesh_loose_mod"``) plus a companion
  ``modinfo.json``, both alongside the same ``files/<vfs-relative-path>``
  layout. This module reproduces that exact schema so `sky2cd` output is
  directly compatible with the same manager audience CrimsonForge itself
  already targets.
"""

from __future__ import annotations

import datetime
import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class DmmAsset:
    """One converted/merged mesh asset going into the package.

    `entry_path` is the real game VFS-relative path the .pac replaces (e.g.
    ``"character/cd_phw_00_lb_00_0182.pac"`` -- forward slashes, no leading
    slash, no package-group folder prefix). `package_group` is the real
    package-group folder name it was found in (e.g. ``"0009"``), for
    informational/manifest purposes only.
    """

    entry_path: str
    pac_bytes: bytes
    package_group: str = ""
    vertices: int = 0
    faces: int = 0
    submeshes: int = 1
    source_obj_path: str = ""
    note: str = ""


@dataclass(frozen=True)
class DmmPackageResult:
    mod_dir: Path
    manifest_path: Path
    modinfo_path: Path
    file_paths: list[Path]
    provenance_path: Path | None = None


@dataclass(frozen=True)
class PackageValidationIssue:
    entry_path: str
    problem: str


@dataclass(frozen=True)
class PackageValidationReport:
    """Result of `validate_dmm_package_inputs`. Never claims body-fit,
    clipping, or animation validity -- only that the supplied bytes are
    structurally sane (CrimsonForge-parseable, when checked) and that the
    real sidecar files a working DMM mod ships alongside its `.pac` are
    present.
    """

    ok: bool
    issues: list[PackageValidationIssue] = field(default_factory=list)
    sha256_by_path: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "ok": self.ok,
            "issues": [{"entry_path": i.entry_path, "problem": i.problem} for i in self.issues],
            "sha256_by_path": dict(self.sha256_by_path),
        }


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def validate_dmm_package_inputs(
    assets: list[DmmAsset],
    extra_files: dict[str, bytes] | None = None,
    *,
    cf=None,
) -> PackageValidationReport:
    """Strict, artist-facing pre-flight validation for an artist-supplied,
    already-rebuilt `.pac` (or set of them) before it's packaged as a DMM mod.

    **Explicitly NOT a fit/clipping/animation check** -- it only verifies:

    - every asset's `.pac` bytes are at least parseable by CrimsonForge's own
      `core.mesh_parser.parse_mesh` (only if `cf`, the namespace from
      `sky2cd.crimsonforge_bridge.load_crimsonforge_modules`, is supplied);
      this catches a truncated/corrupt rebuild before it ships, nothing more.
    - every asset has a matching `<stem>.pac_xml` sidecar present in
      `extra_files` -- every real, working, currently-installed DMM mod
      inspected during this project ships one alongside its `.pac` (material/
      skin bindings); a package missing it is the single most likely reason
      a "real" test mod silently does nothing in-game.

    Always computes a `sha256_by_path` provenance map for every asset (keyed
    by `entry_path`) and extra file (keyed by its relative path) regardless
    of whether validation passes, so a caller can persist exact-bytes
    provenance for an artist-supplied rebuild even when validation fails.
    """
    extra_files = extra_files or {}
    issues: list[PackageValidationIssue] = []
    sha256_by_path: dict[str, str] = {}

    extra_names = {Path(p).name for p in extra_files}
    for asset in assets:
        sha256_by_path[asset.entry_path] = _sha256_hex(asset.pac_bytes)
        expected_xml = f"{Path(asset.entry_path).stem}.pac_xml"
        if expected_xml not in extra_names:
            issues.append(
                PackageValidationIssue(
                    entry_path=asset.entry_path,
                    problem=f"missing required sidecar '{expected_xml}' (material/skin bindings a "
                    "real installed DMM mod always ships alongside its .pac)",
                )
            )
        if cf is not None:
            try:
                cf.mesh_parser.parse_mesh(asset.pac_bytes, filename=asset.entry_path)
            except Exception as exc:  # noqa: BLE001 -- any parser failure is itself the validation issue
                issues.append(
                    PackageValidationIssue(
                        entry_path=asset.entry_path,
                        problem=f"CrimsonForge could not parse this .pac: {exc}",
                    )
                )

    for rel_path, data in extra_files.items():
        sha256_by_path[rel_path] = _sha256_hex(data)

    return PackageValidationReport(ok=not issues, issues=issues, sha256_by_path=sha256_by_path)


def _sanitize_mod_folder_name(title: str) -> str:
    """Turn a display title into a filesystem-safe mod folder name."""
    keep = "".join(c if (c.isalnum() or c in " _-()'") else "_" for c in title)
    keep = keep.strip().replace(" ", "_")
    return keep or "sky2cd_mod"


def _validate_relative_path(rel_path: str) -> None:
    if "\\" in rel_path:
        raise ValueError(f"paths must use forward slashes, got: '{rel_path}'")
    if rel_path.startswith("/") or (len(rel_path) > 1 and rel_path[1] == ":"):
        raise ValueError(f"paths must be relative, got: '{rel_path}'")
    if any(part == ".." for part in rel_path.split("/")):
        raise ValueError(f"paths must not contain '..' segments, got: '{rel_path}'")


def build_dmm_package(
    assets: list[DmmAsset],
    out_dir: str | Path,
    *,
    title: str,
    author: str = "sky2cd",
    version: str = "1.0.0",
    description: str = "",
    game_build: str = "",
    extra_files: dict[str, bytes] | None = None,
    strict: bool = False,
    cf=None,
) -> DmmPackageResult:
    """Write a DMM-compatible loose-file mesh-mod package.

    Args:
        assets: converted/merged .pac assets to include (each replaces one
            real in-game item mesh at its own `entry_path`).
        out_dir: directory to create the mod folder in.
        title: mod display title; also used (sanitized) as the folder name.
        author: mod author string.
        version: mod version string.
        description: mod description string; a sensible default is generated
            if left empty.
        game_build: optional game build/version string for the manifest
            (informational only, e.g. "v2.02.00").
        extra_files: optional additional game-relative files to bundle
            alongside the assets (e.g. copied ``.pac_xml`` material sidecars
            or textures), same path rules as `entry_path`.
        strict: if `True`, run `validate_dmm_package_inputs` BEFORE writing
            anything and raise `ValueError` if it finds any issue (missing
            required `.pac_xml` sidecar, or -- if `cf` is given -- a `.pac`
            CrimsonForge itself can't parse). On success, also writes a
            `provenance.json` (sha256 of every asset + extra file's exact
            bytes, plus the validation report) into the mod folder. Default
            `False` preserves this function's prior behavior exactly (no
            extra validation, no `provenance.json`). Strict mode still makes
            NO claim about body fit, clipping, or animation correctness --
            it only checks structural sanity and sidecar completeness.
        cf: optional CrimsonForge namespace (from `sky2cd.crimsonforge_
            bridge.load_crimsonforge_modules`) used only when `strict=True`,
            to additionally verify each `.pac` parses via CrimsonForge's own
            `core.mesh_parser`. Ignored when `strict=False`.

    Returns:
        DmmPackageResult with the written mod folder, manifest, modinfo,
        file paths, and (only in strict mode) a `provenance_path`.

    Raises:
        ValueError: if `assets` is empty, if any path is absolute, uses
            backslashes, or contains '..' path segments, or (strict mode
            only) if pre-flight validation finds any issue.
    """
    if not assets:
        raise ValueError("assets must not be empty -- nothing to package")

    for asset in assets:
        _validate_relative_path(asset.entry_path)
    for rel_path in (extra_files or {}):
        _validate_relative_path(rel_path)

    validation_report: PackageValidationReport | None = None
    if strict:
        validation_report = validate_dmm_package_inputs(assets, extra_files, cf=cf)
        if not validation_report.ok:
            details = "; ".join(f"{i.entry_path}: {i.problem}" for i in validation_report.issues)
            raise ValueError(f"strict package validation failed: {details}")

    out_dir = Path(out_dir)
    mod_dir = out_dir / _sanitize_mod_folder_name(title)
    files_dir = mod_dir / "files"
    files_dir.mkdir(parents=True, exist_ok=True)

    written_paths: list[Path] = []
    for asset in assets:
        dest = files_dir / asset.entry_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(asset.pac_bytes)
        written_paths.append(dest)

    for rel_path, data in (extra_files or {}).items():
        dest = files_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        written_paths.append(dest)

    created_utc = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")
    if not description:
        description = f"Loose mesh mod generated by sky2cd for {len(assets)} asset(s)."

    manifest = {
        "format": "v1",
        "schema_version": 1,
        "kind": "mesh_loose_mod",
        "game": "Crimson Desert",
        "title": title,
        "name": title,
        "mod_name": title,
        "author": author,
        "version": version,
        "created_utc": created_utc,
        "generator": "sky2cd",
        "generator_url": "https://github.com/sky2cd/sky2cd",
        "game_build": game_build,
        "asset_count": len(assets),
        "file_count": len(written_paths),
        "files_root": "files",
        "assets": [
            {
                "entry_path": asset.entry_path,
                "package_group": asset.package_group,
                "format": "pac",
                "obj_path": asset.source_obj_path,
                "vertices": asset.vertices,
                "faces": asset.faces,
                "submeshes": asset.submeshes,
                "generated_from": "sky2cd",
                "note": asset.note,
            }
            for asset in assets
        ],
        "files": [
            {
                "path": asset.entry_path,
                "package_group": asset.package_group,
                "format": "pac",
                "generated_from": "sky2cd",
                "note": asset.note,
            }
            for asset in assets
        ]
        + [
            {
                "path": rel_path,
                "package_group": "",
                "format": "pac_xml" if rel_path.endswith(".pac_xml") else "texture",
                "generated_from": "sky2cd",
                "note": "unmodified copy of the real game file (donor sidecar)",
            }
            for rel_path in (extra_files or {})
        ],
    }
    manifest_path = mod_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    modinfo = {
        "title": title,
        "name": title,
        "author": author,
        "version": version,
        "game": "Crimson Desert",
        "format": "v1",
        "type": "mesh_loose_mod",
        "description": description,
        "generator": "sky2cd",
        "generator_url": "https://github.com/sky2cd/sky2cd",
        "game_build": game_build,
        "created_utc": created_utc,
    }
    modinfo_path = mod_dir / "modinfo.json"
    modinfo_path.write_text(json.dumps(modinfo, indent=2), encoding="utf-8")

    provenance_path: Path | None = None
    if strict:
        provenance = {
            "generator": "sky2cd",
            "strict_validation": True,
            "note": "sha256 provenance for the exact bytes packaged. Confirms structural sanity "
            "and sidecar completeness ONLY -- does NOT validate body fit, clipping, weight/rig "
            "transfer, or in-game/animation correctness.",
            "created_utc": created_utc,
            "validation": validation_report.to_dict() if validation_report else None,
        }
        provenance_path = mod_dir / "provenance.json"
        provenance_path.write_text(json.dumps(provenance, indent=2), encoding="utf-8")

    return DmmPackageResult(
        mod_dir=mod_dir,
        manifest_path=manifest_path,
        modinfo_path=modinfo_path,
        file_paths=written_paths,
        provenance_path=provenance_path,
    )
